replicaCount: 2

image:
  repository: saydullox/procurement-api
  pullPolicy: IfNotPresent

  # Overrides the image tag whose default is the chart appVersion.
  tag: "284c671d4c788c11b58f7698e9f958f1e2788f81"



service:
  type: ClusterIP
  port: 8080

env:
  - name: ASPNETCORE_URLS
    value: "http://+:8080"

rabbitmq:
  host: rabbitmq
  port: 5672
  username: admin
  password: admin123

ingress:
  enabled: false


# livenessProbe:
#   httpGet:
#     path: /
#     port: 8080
#   initialDelaySeconds: 20
#   periodSeconds: 10

# readinessProbe:
#   httpGet:
#     path: /
#     port: 8080
#   initialDelaySeconds: 20
#   periodSeconds: 10

initContainers:
- name: wait-for-rabbitmq
  image: busybox
  command: ['sh', '-c', 'until nc -z rabbitmq 5672; do echo waiting; sleep 2; done;']

# <<< Shu bo‘limni qo‘shish juda muhim
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""
